# Generated by Django 4.1.7 on 2023-03-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("Residencial", "Residencial"),
                            ("Comercial", "Comercial"),
                            ("Industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_consumption", models.IntegerField()),
                ("max_consumption", models.IntegerField()),
                ("discount", models.FloatField()),
                ("coverage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Nome do Consumidor"),
                ),
                (
                    "document",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="Documento(CPF/CNPJ)"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="CEP"
                    ),
                ),
                ("city", models.CharField(max_length=128, verbose_name="Cidade")),
                ("state", models.CharField(max_length=128, verbose_name="Estado")),
                (
                    "consumption",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Consumo(kWh)"
                    ),
                ),
                (
                    "distributor_tax",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tarifa da Distribuidora"
                    ),
                ),
                ("coverage", models.IntegerField(null=True)),
                ("consumer_type", models.CharField(max_length=50, null=True)),
                (
                    "discount_rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers",
                        to="core.discountrules",
                    ),
                ),
            ],
        ),
    ]
